### ISSUE TITLE
0.5.2 broke current network configuration

### ISSUE THREAD

**Issue by aminvakil** [wolegis/mkinitcpio-systemd-extras#6]
I've just started using this repository and it's brilliant, thank you for it!

But 0.5.2 just broke my system and I cannot access to my server after a reboot as cpio was not installed, I'll whip up a PR for it if it's OK.

**Comment by wolegis** [comment]
I'm flabbergasted that with v0.5.2 your system became inaccessible. I'm having difficulties believing that a missing cpio is the culprit here, because cpio is required for mkinitcpio also. In other words you wouldn't even be able to build a new initramfs image without cpio.

But I had to learn that cpio is NOT a dependency for mkinitcpio. Still have to find out how mkinitcpio can work without it.

Anyway, I've effectively (quick and dirty) rolled back to v0.5.1 by setting another tag v0.5.3 to the very same commit. Changes have already published to AUR.

Thanks for the hint. A proper solution will follow soon.

**Comment by aminvakil** [comment]
No problem, thank you!

Also my problem got fixed after installing cpio in 0.5.2, so :shrug:

**Comment by wolegis** [comment]
I've pushed another version (v0.5.4) where `cpio` got replaced by a combination of a `for` loop and `add_file`. You may have a look at this [diff](https://github.com/wolegis/mkinitcpio-systemd-extras/compare/v0.5.2...v0.5.4) if you are interested.

The reason why I didn't go the easy way by just adding the dependency on `cpio` to `PKBUILD` is the following:

*mkinit-systemd-extras* is a collection of install hooks for `mkinitcpio`. People may choose one or another hook by naming those in the `HOOKS` array in their `/etc/mkinitcpio.conf`. People may NOT use the `sd-network` hook, but a dependency on `cpio` would nevertheless pull in this tool - although not required by those guys.

So I'm trying to avoid hard dependencies wherever possible. If really required by some hook I will name a dependency in `optdepends` together with a short hint on the hook.
